#!/usr/bin/env bash
# Assemble PeterFan.app — a macOS menu-bar agent bundle around the
# peterfan-menubar binary.
#
# Usage:
#   scripts/bundle-macos.sh [BINARY] [OUTDIR]
#     BINARY  path to the built peterfan-menubar (default: target/release/peterfan-menubar)
#     OUTDIR  where to write PeterFan.app   (default: dist)
#   VERSION=0.8.0 scripts/bundle-macos.sh   # stamps the bundle version
#
# LSUIElement=true makes it an "accessory" app: a menu-bar item with no Dock
# icon.
#
# The bundle is signed at the end. By default this is ad-hoc so local/fork
# builds still work; set PETERFAN_SIGN_IDENTITY to a Developer ID Application
# identity to produce a notarization-ready distribution build.

set -euo pipefail

# shellcheck disable=SC1091
source "$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/scripts/load-env.sh"

BIN="${1:-target/release/peterfan-menubar}"
OUTDIR="${2:-dist}"
VERSION="${VERSION:-0.0.0}"
BUNDLE_ID="${PETERFAN_BUNDLE_ID:-kr.co.uulab.peterfan}"
APP="$OUTDIR/PeterFan.app"

if [[ ! -x "$BIN" ]]; then
  echo "error: binary not found at '$BIN' (build it first: cargo build --release)" >&2
  exit 1
fi

rm -rf "$APP"
mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources"
cp "$BIN" "$APP/Contents/MacOS/PeterFan"
chmod +x "$APP/Contents/MacOS/PeterFan"

# Bundle peterfand alongside the menu-bar binary so the in-app "Enable Fan
# Control" menu item can find and install it without a terminal — it looks
# next to its own executable (see peterfan_platform::daemon_install).
PETERFAND="$(dirname "$BIN")/peterfand"
if [[ -x "$PETERFAND" ]]; then
  cp "$PETERFAND" "$APP/Contents/MacOS/peterfand"
  chmod +x "$APP/Contents/MacOS/peterfand"
else
  echo "warning: peterfand not found at '$PETERFAND' — 'Enable Fan Control' won't work in this bundle" >&2
fi

# App icon (optional — generated by scripts/make-icns.sh).
ICON_LINE=""
if [[ -f assets/AppIcon.icns ]]; then
  cp assets/AppIcon.icns "$APP/Contents/Resources/AppIcon.icns"
  ICON_LINE="  <key>CFBundleIconFile</key><string>AppIcon</string>"
fi

cat > "$APP/Contents/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleName</key><string>PeterFan</string>
  <key>CFBundleDisplayName</key><string>PeterFan</string>
  <key>CFBundleIdentifier</key><string>${BUNDLE_ID}</string>
  <key>CFBundleExecutable</key><string>PeterFan</string>
${ICON_LINE}
  <key>CFBundlePackageType</key><string>APPL</string>
  <key>CFBundleVersion</key><string>${VERSION}</string>
  <key>CFBundleShortVersionString</key><string>${VERSION}</string>
  <key>LSMinimumSystemVersion</key><string>11.0</string>
  <key>LSUIElement</key><true/>
  <key>NSHighResolutionCapable</key><true/>
  <key>NSHumanReadableCopyright</key><string>MIT © PeterFan contributors</string>
</dict>
</plist>
PLIST

# Validate the plist if the tool is available.
if command -v plutil >/dev/null 2>&1; then
  plutil -lint "$APP/Contents/Info.plist" >/dev/null
fi

# Sign the bundle. Best-effort: codesign is macOS-only and this script may run
# in cross-platform CI contexts that lack it.
if command -v codesign >/dev/null 2>&1; then
  scripts/sign-macos.sh "$APP" 2>&1 | sed 's/^/  codesign: /' || \
    echo "warning: codesign failed — bundle will still work locally but downloaded copies will trigger Gatekeeper friction" >&2
fi

# Nudge Finder/LaunchServices to drop any cached icon for this bundle path —
# rebuilding in place at the same path with the same bundle identifier is
# exactly the case where macOS's icon cache goes stale and keeps showing a
# blank/generic icon even after a real AppIcon.icns lands on disk.
LSREGISTER="/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister"
if [[ -x "$LSREGISTER" ]]; then
  "$LSREGISTER" -f "$APP" >/dev/null 2>&1 || true
fi
touch "$APP"

echo "built $APP (version $VERSION)"
